Adicionando ApTextInput, ApPasswordInput, Formik e Vector Icons com IcoMoon
capsicum-annuum/app pull request #6
Opened 2020-04-12 19:55 UTC by edersonmberti

O ApTextInput pode receber, além das propriedades normal de um TextInput, as propriedades optional, aditional, aditionalCallback, alert, alertCallback.

Optional renderiza o texto "Opcional" no canto direito do campo. 
Aditional renderiza a opcão de "Help" no canto direito do campo. Caso o usuário clique no icone de "help", é disparado o aditionalCallback.
Alert renderiza o icone de alerta esquerdo e fora do campo. Caso o usuário clique no icone de "alert", é disparado o alertCallback.

Caso ele receba optinal=true e aditional=true, o texto de "opcioal" renderiza um pouco mais para dentro do componente, aparecendo os dois ao mesmo tempo.

Caso o usuário digite algum valor em um campo opcional, o texto "Opcional" some.

Adicionei também o Formik para o gerenciamento dos fomulários. Em uma próxima task irei adicional o Yup para a validação dos campos.

Além disso, foi adicionado o Vector Icons utilizando um arquivo de fontes custom. 
Para adicionar um novo icone, é necessário subir o arquivo section.json que fica dentro da pasta assets/fonts no site do IcoMoon, aí adicionar o icone, exportar o novo arquivo e subistituir os dois arquivos que estão dentro da pasta assets/fonts pelos novos. 

Qualquer dúvida é só dar um grito que eu explico o passo a passo de como subir um novo icone.

Escolhi o IcoMoon pois parece ser uma maneira segura de manter a qualidade dos icones e da forma que trabalhamos com eles dentro do app. 

Tmj

#LavemAsMãos
#HandsOn

2020-04-12 21:08 UTC, robsonrosa commented on src/components/ap-icon/ap-icon.component.js
> +const expoAssetId = require('../../assets/fonts/HandsOn.ttf')
Não sei se eu entendi... Todos os ícones ficam dentro desse `.ttf`?

2020-04-12 21:14 UTC, robsonrosa commented on src/components/ap-text-input/ap-text-input.component.js
> +    </View>
Que a fude!!! 👏

2020-04-12 21:17 UTC, robsonrosa requested changes
Só fico um pouco preocupado com os estilos muitos espalhados por toda aplicação. Penso se não vai ser muito complicado ajustar isso após mudanças no design, até por que, no início agora, tende a ter várias mudanças até fechar um padrão certinho.

2020-04-12 21:17 UTC, robsonrosa commented on src/components/ap-text-input/ap-text-input.style.js
> +    color: '#B9E8E6',
Não da pra usar variáveis pras cores? Não só cores, ter "perfis" de fontes e cores. Tipo "fonte principal", "fonte auxiliar" enfim...

2020-04-12 23:43 UTC, edersonmberti commented on src/components/ap-text-input/ap-text-input.style.js
> +    color: '#B9E8E6',
Eras sim. Pensei em separar uma task para definir os themas, cores e fontes.

2020-04-12 23:45 UTC, edersonmberti commented on src/components/ap-icon/ap-icon.component.js
> +const expoAssetId = require('../../assets/fonts/HandsOn.ttf')
Isso mesmo. Ai pra adicionar um novo icon precisa ser atualizado os dois arquivos.

2020-04-13 04:40 UTC, robsonrosa commented on src/components/ap-text-input/ap-text-input.style.js
> +    color: '#B9E8E6',
Pode crer! Acho que vale uma task separada pra isso. 

Task: https://trello.com/c/KhVFR3es/87-temas

2020-04-13 04:41 UTC, robsonrosa approved these changes

2020-04-13 04:42 UTC, merged