Feat/reusable button
capsicum-annuum/app pull request #7
Opened 2020-04-16 01:19 UTC by DionataSilva

2020-04-16 03:51 UTC, robsonrosa requested changes
Fiquei em dúvida em alguns pontos, mais pela minha falta de conhecimento mesmo em react native mesmo.

2020-04-16 03:51 UTC, robsonrosa commented on src/components/ap-button/ap-button.component.js
> +  const buttonColor = !light ? secondaryColor : enable ? primaryColor : secondaryColor
`enable && light ? primaryColor : secondaryColor`

Não daria na mesma?

2020-04-16 03:51 UTC, robsonrosa commented on src/components/ap-button/ap-button.component.js
> +  }, [props])
Não podermos assumir que as configurações do botão (texto e estilos) não vão mudr durante um ciclo? Daí poderíamos apenas observar a prop do loading e o enable

2020-04-16 03:51 UTC, robsonrosa commented on src/components/ap-button/ap-button.component.js
> +  const opacity = enable ? 1 : 0.4
Acho que `enabled` seria melhor

2020-04-16 03:51 UTC, robsonrosa commented on src/components/ap-button/ap-button.component.js
> +        onPress={() => onPress()}
precisa dessa arrow function? Não poderia ser simplesmente `onPress={onPress}` ?

2020-04-16 03:51 UTC, robsonrosa commented on src/components/ap-button/ap-button.styles.js
> +    borderRadius: 50,
Não deveria ser `%`?

2020-04-16 23:02 UTC, DionataSilva commented on src/components/ap-button/ap-button.component.js
> +  const buttonColor = !light ? secondaryColor : enable ? primaryColor : secondaryColor
Dá sim. Só quis complicar um pouquinho

2020-04-16 23:03 UTC, DionataSilva commented on src/components/ap-button/ap-button.component.js
> +  const opacity = enable ? 1 : 0.4
verdade

2020-04-16 23:03 UTC, DionataSilva commented on src/components/ap-button/ap-button.component.js
> +        onPress={() => onPress()}
Verdade! Não precisa mesmo.

2020-04-16 23:17 UTC, DionataSilva commented on src/components/ap-button/ap-button.styles.js
> +    borderRadius: 50,
Nesse caso estou me referindo a pixel e não em porcentagem, por isso é só 50 mesmo.

2020-04-16 23:25 UTC, DionataSilva commented on src/components/ap-button/ap-button.component.js
> +  }, [props])
Na aplicação temos na maioria dos casos as mesmas duas cores de botão, porém em casos específicos, como na autenticação via Facebook essa cor muda. Fiz dessa forma pensando nisso.  Vale ressaltar que as props "**primaryColor**" e "**secondaryColor**" são opcionais, assim como "**light**", "**enabled**" e "**loading**".

2020-04-20 20:27 UTC, edersonmberti commented on src/components/ap-button/ap-button.component.js
> +        disabled={!enabled}
Não seria legal se caso o loading estiver em true o botão ficar disabled também?

2020-04-20 22:56 UTC, DionataSilva commented on src/components/ap-button/ap-button.component.js
> +        disabled={!enabled}
Tá na mão

2020-04-20 22:59 UTC, merged